### PR TITLE
GitHub actions

### LINKED ISSUE #8: Analyze Github Actions
- Try out Github Actions
- Document how we can use it for this project

### PR DESCRIPTION
**Pull request by neontvn**

### CODE REVIEW

**Comment by Kshitijde** [comment]
This change involves writing a GitHub Action for generating documentation for the existing code and hosting it on Github Pages: https://cse210-fa24-group13.github.io/codesnip/

**Comment by rohanthorat27** [comment]
Conflict in package-lock.json?

**Comment by Kshitijde** [comment]
ya, I checked marked dependancy is coming due to typedocs , lru-cache is coming due to typescript-eslint

**Review by mokshitagupta — APPROVED** [review]
the fix seems to work!

**Review by rohanthorat27 — APPROVED** [review]
Looks good!

**Comment by neontvn** [comment]
@Kshitijde It says there are 68 files changed? I think it includes the docs folder. Can you please add it to .gitignore file unless we require it to be checked in to master as well?

**Comment by Kshitijde** [comment]
It can't be added in the gitignore as this will prevent the github bot from adding the documentation post a push to the main branch

**Comment by neontvn** [comment]
> It can't be added in the gitignore as this will prevent the github bot from adding the documentation post a push to the main branch

Got it. You can go ahead and merge it to main then.

**Pull request merged**
