### PR TITLE
Sprint 3 Review 

### PR DESCRIPTION
**Pull request by Jyotikakakar**

### CODE REVIEW

**Review by mokshitagupta — APPROVED** [review]
Very nicely structured, gives a great overview of sprint 3! thanks Jyotika

**Review by FudeCao — COMMENTED** [review]
Looks good, very detailed

**Review by rohanthorat27 — APPROVED** [review]
looks good

**Review by angusyick — APPROVED** [review]
Good sprint this week!

**Review by neontvn — APPROVED** [review]
Last sprint was a very productive sprint! Looking forward to this sprint!

**Pull request merged**
