### PR TITLE
Added CI/CD Pipeline Progress Report

### LINKED ISSUE #15: As a team, document the CI/CD pipeline setup

### PR DESCRIPTION
**Pull request by neontvn**

### CODE REVIEW

**Comment by Kshitijde** [comment]
The sentence describing the "analysis" in ESLint is not intuitively clear, can we rephrase that to include something along the lines of catching potential errors? 

Everything else looks good to me! The diagram is clear and simple which I really liked!

**Review by Kshitijde — APPROVED** [review]

**Comment by neontvn** [comment]
Updated the documentation.

**Review by FudeCao — APPROVED** [review]
Looks good to me. If we have no experience with E2E testing, we'd better start it early.

**Review by mokshitagupta — APPROVED** [review]
looks good to me!

**Comment by rohanthorat27** [comment]
Looks good.

**Comment by angusyick** [comment]
I think everything looks good

**Pull request merged**
