### PR TITLE
Create docs folder and add VSCode_Linter.pdf

### PR DESCRIPTION
**Pull request by YingJiehXia**

### CODE REVIEW

**Comment by neontvn** [comment]
The existing project does use ESLint. 
Can you please add a few lines mentioning regarding this in the file? Just so that we have it documented.

**Comment by YingJiehXia** [comment]
Ok added!

**Comment by Kshitijde** [comment]
So just to summarize, you are suggesting that we use : 

1) ESLint for linting
2) Prettier for formatting
3) Babel JS for syntax highlighting

Sounds good to me!

**Review by Kshitijde — APPROVED** [review]

**Review by neontvn — APPROVED** [review]
We will not be changing the existing ESLint linter that is being used

**Pull request merged**
