### PR TITLE
Adding MD file instead of PDF in specs>adrs

### PR DESCRIPTION
**Pull request by rohanthorat27**
The PDFs in specs>docs need to be removed in main.

### CODE REVIEW

**Comment by neontvn** [comment]
Can you rename the file as 01_name_of_file.md?

**Comment by neontvn** [comment]
Also, please update the pull request with the latest of main.

**Comment by Kshitijde** [comment]
Looks good to me!

**Comment by rohanthorat27** [comment]
@neontvn all done.

**Review by neontvn — APPROVED** [review]

**Pull request merged**
