### PR TITLE
Create 113024-sprint-3-retrospective.md

### PR DESCRIPTION
**Pull request by mokshitagupta**

### CODE REVIEW

**Review by rohanthorat27 — APPROVED** [review]
Nice

**Comment by neontvn** [comment]
Can we also add resolutions to the lacked points as we discussed in the meeting? We can just mention it in a line or two.

**Review by FudeCao — COMMENTED** [review]
Good.

**Review by rohanthorat27 — APPROVED** [review]
looks good

**Review by angusyick — APPROVED** [review]
Good sprint this week!

**Pull request merged**
