### PR TITLE
Search functionality

### PR DESCRIPTION
**Pull request by rohanthorat27**

### CODE REVIEW

**Review by neontvn — COMMENTED** [review]
changes looks good to me! 

I think we should consider moving the JS code to a separate file for better readability? What do you think?

**Comment by rohanthorat27** [comment]
Can be done. We can even have a different file for the CSS.

**Comment by neontvn** [comment]
should not be a big change. Can we do that as well, as part of this task?

**Comment by rohanthorat27** [comment]
Sure I can do it tomorrow after standup

**Comment by Kshitijde** [comment]
Ya makes sense, let us separate the files, it's easier to understand for a new person who might join the team (hypothetically) later on, too.. and ensures that we don't have like very long files. Apart from that, it looks good! I liked the look and feel

**Comment by rohanthorat27** [comment]
Please check, I have created separate files for the scripts and styling. If it looks good then merge.

**Comment by Kshitijde** [comment]
Yep, looks good to me now...all set to merge

**Review by Kshitijde — APPROVED** [review]

**Pull request merged**
