### PR TITLE
Added proposed features and enhancements documentation

### PR DESCRIPTION
**Pull request by rohanthorat27**

### CODE REVIEW

**Comment by neontvn** [comment]
Just to confirm the features that have been listed are in the decreasing order of priority, right?
Otherwise looks good to me.

**Comment by FudeCao** [comment]
> Just to confirm the features that have been listed are in the decreasing order of priority, right? Otherwise looks good to me.

No. After discussion, we found that we cannot decide the implementation difficulty. There exist some obviously difficult tasks in the list.

**Review by neontvn — COMMENTED** [review]
Looks good to me.

**Comment by Kshitijde** [comment]
I think this a good collection of features. However, I also think that most functionalities mentioned here have a bad development effort/utility ratio. I think we should delve deeper and focus on the following features :
1) Sharing (explore current options in the extension and extend that)
2) The shortcut keys feature seems doable and feels useful to me

Research for various features is good though! PR looks good to me for closing

**Review by Kshitijde — APPROVED** [review]

**Pull request merged**
