### PR TITLE
Merging github authentication feature to Fude's Gist branch

### PR DESCRIPTION
**Pull request by rohanthorat27**
@FudeCao could you resolve the conflict once you go through the code. Thanks.

### CODE REVIEW

**Comment by FudeCao** [comment]
Don't merge this. I used personal access token and we decided to use temporary authentication token.

**Comment by neontvn** [comment]
@rohanthorat27 @YingJiehXia please make sure your branch is up-to date with main branch and also Fude_gist

**Comment by neontvn** [comment]
> Don't merge this. I used personal access token and we decided to use temporary authentication token.

We will be using your branch as the main branch for this functionality. We will need the changes done by Rohan to be able to implement the logic to use the OAuth token to make the api calls.

**Comment by neontvn** [comment]
> @rohanthorat27 @YingJiehXia please make sure your branch is up-to date with main branch.

I have updated the Fude_gist branch with latest of main

**Comment by rohanthorat27** [comment]
> @rohanthorat27 @YingJiehXia please make sure your branch is up-to date with main branch and also Fude_gist

Done.

**Comment by Kshitijde** [comment]
image
Could you please take a look @rohanthorat27 ..check if test github auth options is required

**Comment by rohanthorat27** [comment]
> image Could you please take a look @rohanthorat27 ..check if test github auth options is required

Done

**Comment by neontvn** [comment]
@rohanthorat27 @YingJiehXia you might have to check the eslint.config.js once to fix the linting error. Also, please check if the tests are running successfully on local. Drop a message to me or @Kshitijde in case you are facing any issues.

**Comment by rohanthorat27** [comment]
Thank you @YingJiehXia 
@neontvn @Kshitijde take a look

**Comment by Kshitijde** [comment]
Could we quickly jump on a call and discuss the changes made? I have a few questions

**Pull request closed without merging**
