### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by YingJiehXia**
Updated dependencies and fixed the errors.

### CODE REVIEW

**Review by Kshitijde — COMMENTED** [review]
"@typescript-eslint/semi": "warn",

Why is this line commented in the newly proposed JSON config file?

**Comment by neontvn** [comment]
> "@typescript-eslint/semi": "warn",
> 
> Why is this line commented in the newly proposed JSON config file?

not supported in latest version of eslint config, removed it. We already have "semi" that is used for the same purpose.

**Comment by ChrisChen0803** [comment]
It looks good to me.

**Review by ChrisChen0803 — APPROVED** [review]
Shows updated dependencies, it looks good to me

**Review by Kshitijde — APPROVED** [review]
coool, looks good then!

**Comment by Kshitijde** [comment]
Looks like there a few conflicts, take a look so that we can merge this today! @neontvn @YingJiehXia

**Pull request merged**
